### ISSUE TITLE
cannot use JSR-303 Bean Validation Annotations: javax.validation.UnexpectedTypeException

### ISSUE THREAD

**Issue by civilizeddev** [vavr-io/vavr-beanvalidation2#9]
- Given
  ```
  ... (in a class)
  @Length(max = 35)
  Option<String> someField;
  ```

- When
  ```
  // try validation
  Validator.validate(obj);
  ```

- Then
  ```
  HV000030: No validator could be found for constraint 'org.hibernate.validator.constraints.Length' 
  validating type 'io.vavr.control.Option<java.lang.String>'.
  ```

**Comment by alwins0n** [comment]
Thanks for reporting. out of curiosity: could you try to annotate the type parameter instead?

e.g. `Option<@Length(max = 35) String> someField` 

does this work?

**Comment by alwins0n** [comment]
Wow this issue is from 2017. Far before vavr-beanvalidation 2.0 existed. Is this how we treat our users @mincong-h ? by deferring issues to barely related projects after 3(!) years? 

ping @danieldietrich

**Comment by danieldietrich** [comment]
@mincong-h has my full backup, he is one of the most engaged committers! Thank you Mincong 🙏🏻

We do not have any kind of SLA, the Vavr sub-projects rely heavily on contributions.

This issue is bean validation related, it makes sense to place it here. If we can't solve it or it is more related to 3rd party tooling, I suggest to close it and refer to our Gitter chat. It is never too late :)

**Comment by alwins0n** [comment]
I myself am a heavy user of vavr-jackson and I am happy that @mincong-h provided a solid plugin for that.

But this has nothing to do with the careless treatment of this nonsensical issue, which so far did nothing but cost me time.

Closed

**Comment by danieldietrich** [comment]
> so far did nothing but cost me time

I have been there, welcome to open source :)

> I am happy that @mincong-h provided a solid plugin for that

@ruslansennov created vavr-jackson! Mincong joined us and takes care of the quality of several projects. He is one of the most careful and precious committers I know. Be friendly to each other.

**Comment by mincong-h** [comment]
Hi @alwins0n , sorry about the transfer. I should have asked your opinion before doing so and I will surely do for the next time. If you have any other advice, I will be happy to hear as well. I didn't know about Vavr back to 2017 and tried to better categorize the issue yesterday. By the way, thank you @danieldietrich for your kind words. Best, Mincong
